---
title: "GDPR_Fines"
output: 
  flexdashboard::flex_dashboard:
    theme: cosmo
    orientation: columns
    vertical_layout: scroll
    navbar:
      - { title: "Help", icon: "fa-life-ring", href: "https://cviewllc.com/contact-us/" 
       }

---


```{r}
library(tidyverse)
library(readr)
library(lubridate)
library(ggplot2)
library(scales)
```



```{r}
gdpr_violations <- readr::read_tsv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-21/gdpr_violations.tsv') %>% 
  rename(country = name) %>% 
  mutate(date = na_if(mdy(date), "1970-01-01"))

gdpr_text <- read_tsv("./Input/gdpr_text.tsv")
```

# GDPR Fines by Country
```{r}
gdpr_violations %>%
  mutate(type = fct_lump(type, 8, w = price),
         type = fct_reorder(type, price),
         country = fct_lump(country, 5)) %>%
  ggplot(aes(price, type)) +
  geom_boxplot() +
  geom_jitter(aes(color = country), width = 0, height = .25) +
  scale_x_log10(labels = dollar_format())
```


```{r}

top_articles_violated <- separated_articles %>% 
                          select(article_violated, article, price, price_per_article) %>% 
                          group_by(article) %>% 
                          summarize(Count = n(),
                                    Avg = mean(price)) %>% 
                          arrange(-Count) %>% 
                          head(5)

gdpr_violations %>%
  filter(price < 1*1e6) %>% 
  separate_rows(article_violated, sep = "\\|") %>%
  extract(article_violated, "article", "Art\\. ?(\\d+)", convert = TRUE, remove = FALSE) %>%
  left_join(article_titles, by = "article") %>%
  mutate(article_title = paste0(article, ". ", str_trunc(article_title, 50)),
         article_title = ifelse(is.na(article), "Unknown", article_title)) %>%
  add_count(id) %>%
  filter(article %in% top_articles_violated$article) %>% 
  mutate(price_per_article = price / n) %>% 
  group_by(date, article_title) %>%
  summarize(violations = n(),
            total_fine = sum(price)) %>%
  ggplot(aes(date, total_fine, size = violations, color = article_title)) +
  geom_point() +
  scale_y_continuous(labels = dollar_format()) +
  scale_size_continuous(guide = FALSE) +
  labs(title = "Vodafone's GDPR violations",
       color = "",
       x = "Time",
       y = "Total fine on this day")
```


```{r}
top_articles_violated <- separated_articles %>% 
                          select(article_violated, article, price, price_per_article) %>% 
                          group_by(article) %>% 
                          summarize(Count = n(),
                                    Avg = mean(price)) %>% 
                          arrange(-Count) %>% 
                          head(9)

gdpr_violations %>%
  filter(price < 10*1e6) %>% 
  separate_rows(article_violated, sep = "\\|") %>%
  extract(article_violated, "article", "Art\\. ?(\\d+)", convert = TRUE, remove = FALSE) %>%
  left_join(article_titles, by = "article") %>%
  mutate(article_title = paste0(article, ". ", str_trunc(article_title, 50)),
         article_title = ifelse(is.na(article), "Unknown", article_title)) %>%
  add_count(id) %>%
  filter(article %in% top_articles_violated$article) %>% 
  mutate(price_per_article = price / n) %>% 
  mutate(month = floor_date(date, unit = "quarter")) %>% 
  group_by(month, article_title) %>%
  summarize(violations = n(),
            total_fine = sum(price)) %>%
  ggplot(aes(month, total_fine, fill = article_title)) +
  geom_col() +
  facet_wrap(~article_title, scales = "free_y") +
  scale_y_continuous(labels = dollar_format(prefix = "")) +
  scale_size_continuous(guide = FALSE) +
  theme(legend.position = "none") +
  labs(title = "GDPR Violations",
       subtitle = "by Article",
       color = "",
       x = "",
       y = "Total Amount (€)")
```



# GDPR Fines by Article
```{r}

article_titles <- gdpr_text %>%
  distinct(article, article_title)

separated_articles <- gdpr_violations %>%
  separate_rows(article_violated, sep = "\\|") %>%
  extract(article_violated, "article", "Art\\. ?(\\d+)", convert = TRUE, remove = FALSE) %>%
  left_join(article_titles, by = "article") %>%
  mutate(article_title = paste0(article, ". ", str_trunc(article_title, 50)),
         article_title = ifelse(is.na(article), "Unknown", article_title)) %>%
  add_count(id) %>%
  mutate(price_per_article = price / n)

separated_articles %>%
  group_by(article = fct_lump(article_title, 8, w = price)) %>%
  summarize(total_fine = sum(price_per_article),
            violations = n()) %>%
  arrange(desc(total_fine)) %>%
  mutate(article = fct_reorder(article, total_fine)) %>%
  ggplot(aes(total_fine, article)) +
  geom_col() +
  scale_x_continuous(labels = dollar_format()) +
  labs(title = "What articles got the most fines?",
       y = "",
       x = "Total fine")

separated_articles %>% 
  select(article_violated, article, price, price_per_article) %>% 
  group_by(article) %>% 
  summarize(Count = n(),
            Avg = mean(price)) %>% 
  arrange(-Count)

```

## Article 5
```{r}
separated_articles %>% 
  filter(article == 5) %>% 
  select(summary, price) %>% view()
```


